create extension if not exists btree_gist with schema extensions;

create table public.rooms (
  id text primary key,
  slug text not null unique,
  name text not null,
  location text not null default '',
  enabled boolean not null default true,
  purpose text not null,
  compact_description text not null,
  recommended_uses jsonb not null default '[]'::jsonb
    check (jsonb_typeof(recommended_uses) = 'array'),
  guidelines jsonb not null default '[]'::jsonb
    check (jsonb_typeof(guidelines) = 'array'),
  booking_increment_minutes integer not null
    check (booking_increment_minutes > 0),
  minimum_duration_minutes integer not null
    check (minimum_duration_minutes > 0),
  maximum_duration_minutes integer not null
    check (maximum_duration_minutes >= minimum_duration_minutes),
  allowed_durations_minutes integer[],
  capacity_label text not null default '',
  display_order smallint not null unique
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  token_hash text not null unique
    check (token_hash ~ '^[0-9a-f]{64}$'),
  reference text not null unique
    check (length(reference) between 3 and 40),
  room_id text not null
    constraint bookings_room_id_fkey references public.rooms(id),
  booking_date date not null,
  start_slot integer not null check (start_slot >= 0 and start_slot < 40),
  end_slot integer not null check (end_slot > start_slot and end_slot <= 40),
  name text not null check (length(btrim(name)) between 1 and 80),
  title text not null check (length(btrim(title)) between 1 and 100),
  email text not null default '' check (length(email) <= 120),
  notes text not null default '' check (length(notes) <= 500),
  status text not null default 'confirmed'
    check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.room_blocks (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id),
  block_date date not null,
  start_slot integer not null check (start_slot >= 0 and start_slot < 40),
  end_slot integer not null check (end_slot > start_slot and end_slot <= 40),
  reason text not null default 'Unavailable',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index bookings_availability
  on public.bookings (booking_date, room_id, status, start_slot, end_slot);
create index room_blocks_availability
  on public.room_blocks (block_date, room_id, active, start_slot, end_slot);

alter table public.bookings
  add constraint bookings_no_overlap
  exclude using gist (
    room_id with =,
    booking_date with =,
    int4range(start_slot, end_slot, '[)') with &&
  )
  where (status = 'confirmed');

create or replace function public.playbook_lock_key(
  p_room_id text,
  p_date date
)
returns bigint
language sql
immutable
strict
set search_path = ''
as $$
  select pg_catalog.hashtextextended(p_room_id || ':' || p_date::text, 0);
$$;

create or replace function public.enforce_booking_rules()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  room_config public.rooms%rowtype;
  duration_minutes integer;
begin
  if new.status <> 'confirmed' then
    return new;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    public.playbook_lock_key(new.room_id, new.booking_date)
  );

  if extract(isodow from new.booking_date) in (5, 6) then
    raise exception using errcode = 'P0001', message = 'WEEKEND_CLOSED';
  end if;

  select *
    into room_config
    from public.rooms
   where id = new.room_id
     and enabled = true;
  if not found then
    raise exception using errcode = 'P0001', message = 'ROOM_INACTIVE';
  end if;

  duration_minutes := (new.end_slot - new.start_slot) * 15;
  if duration_minutes < room_config.minimum_duration_minutes
     or duration_minutes > room_config.maximum_duration_minutes
     or duration_minutes % room_config.booking_increment_minutes <> 0
     or (
       room_config.allowed_durations_minutes is not null
       and not (
         duration_minutes = any(room_config.allowed_durations_minutes)
       )
     )
  then
    raise exception using errcode = 'P0001', message = 'BOOKING_DURATION';
  end if;

  if exists (
    select 1
      from public.room_blocks blocked
     where blocked.active = true
       and blocked.room_id = new.room_id
       and blocked.block_date = new.booking_date
       and new.start_slot < blocked.end_slot
       and new.end_slot > blocked.start_slot
  ) then
    raise exception using errcode = 'P0001', message = 'ROOM_BLOCKED';
  end if;

  return new;
end;
$$;

create trigger bookings_enforce_rules
before insert or update of
  room_id, booking_date, start_slot, end_slot, status
on public.bookings
for each row execute function public.enforce_booking_rules();

create or replace function public.enforce_room_block_rules()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.active <> true then
    return new;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    public.playbook_lock_key(new.room_id, new.block_date)
  );

  if exists (
    select 1
      from public.bookings booking
     where booking.status = 'confirmed'
       and booking.room_id = new.room_id
       and booking.booking_date = new.block_date
       and new.start_slot < booking.end_slot
       and new.end_slot > booking.start_slot
  ) then
    raise exception using errcode = 'P0001', message = 'BLOCK_CONFLICT';
  end if;

  return new;
end;
$$;

create trigger room_blocks_enforce_rules
before insert or update of
  room_id, block_date, start_slot, end_slot, active
on public.room_blocks
for each row execute function public.enforce_room_block_rules();

create or replace function public.create_booking(
  p_token_hash text,
  p_reference text,
  p_room_id text,
  p_booking_date date,
  p_start_slot integer,
  p_end_slot integer,
  p_name text,
  p_title text,
  p_email text,
  p_notes text,
  p_timestamp timestamptz
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  booking_id bigint;
begin
  insert into public.bookings (
    token_hash, reference, room_id, booking_date, start_slot, end_slot,
    name, title, email, notes, status, created_at, updated_at
  ) values (
    p_token_hash, p_reference, p_room_id, p_booking_date, p_start_slot,
    p_end_slot, p_name, p_title, p_email, p_notes, 'confirmed',
    p_timestamp, p_timestamp
  )
  returning id into booking_id;
  return booking_id;
end;
$$;

create or replace function public.update_booking(
  p_booking_id bigint,
  p_room_id text,
  p_booking_date date,
  p_start_slot integer,
  p_end_slot integer,
  p_name text,
  p_title text,
  p_email text,
  p_notes text,
  p_timestamp timestamptz
)
returns bigint
language plpgsql
set search_path = ''
as $$
begin
  update public.bookings
     set room_id = p_room_id,
         booking_date = p_booking_date,
         start_slot = p_start_slot,
         end_slot = p_end_slot,
         name = p_name,
         title = p_title,
         email = p_email,
         notes = p_notes,
         updated_at = p_timestamp
   where id = p_booking_id
     and status = 'confirmed';
  if not found then
    raise exception using errcode = 'P0001', message = 'BOOKING_CANCELLED';
  end if;
  return p_booking_id;
end;
$$;

create or replace function public.cancel_booking(
  p_booking_id bigint,
  p_timestamp timestamptz
)
returns bigint
language plpgsql
set search_path = ''
as $$
begin
  update public.bookings
     set status = 'cancelled',
         updated_at = p_timestamp
   where id = p_booking_id;
  if not found then
    raise exception using errcode = 'P0001', message = 'BOOKING_NOT_FOUND';
  end if;
  return p_booking_id;
end;
$$;

insert into public.rooms (
  id, slug, name, location, enabled, purpose, compact_description,
  recommended_uses, guidelines, booking_increment_minutes,
  minimum_duration_minutes, maximum_duration_minutes,
  allowed_durations_minutes, capacity_label, display_order
) values
(
  'boardroom',
  'meeting-room',
  'Meeting Room',
  '',
  true,
  'Standard meetings for 2–7 people.',
  'Standard meetings for 2–7 people.',
  '["Group working meetings","Team meetings","Client meetings","Interviews","Onboarding sessions","Group discussions"]'::jsonb,
  '["Not intended for solo work.","Not intended for long individual calls.","Use desk-side meetings or Quiet Pods for quick 1:1 meetings when possible.","Keep the room clean.","Remove personal items after the booking."]'::jsonb,
  15, 15, 120, null, '2–7 people', 1
),
(
  'meeting-a',
  'standing-workstations',
  'Standing Workstations',
  'Middle Meeting Room',
  true,
  'Quick tasks, fast check-ins, and short 1:1 conversations.',
  'Quick tasks, fast check-ins, and short 1:1s.',
  '["Quick tasks","Brief check-ins","Short 1:1 conversations","Temporary standing work"]'::jsonb,
  '["Not intended for full meetings.","Not intended for long calls.","Standing use is preferred.","Do not remain there for extended work.","Return to the main desk after use.","Keep the area clear and tidy."]'::jsonb,
  15, 15, 60, array[15,30,45,60], '', 2
),
(
  'meeting-b',
  'innovation-hub',
  'Innovation Hub',
  '',
  true,
  'Brainstorming, creativity, workshops, and strategy sessions.',
  'Brainstorming, workshops, creativity, and strategy.',
  '["Brainstorming","Creative sessions","Workshops","Strategy sessions","Collaborative planning","Energetic group discussions"]'::jsonb,
  '["Intended for collaboration.","Not intended for solo work.","Furniture may be moved during the session.","Furniture must be returned to its original position afterward.","Clean whiteboards after use.","Keep noise within a reasonable level.","Remove sticky notes, papers, and materials after the session."]'::jsonb,
  15, 15, 120, null, '', 3
),
(
  'quiet-pods',
  'quiet-pods',
  'Quiet Pods',
  '',
  true,
  'Quick 1:1s, short internal conversations, focused work, calls, and meals.',
  'Quick 1:1s, focused work, short calls, and internal chats.',
  '["Quick 1:1 meetings","Short internal conversations","Focused individual work","1:1 Zoom calls","Small conversations involving 2–3 people","Short meal breaks"]'::jsonb,
  '["Keep voice volume moderate.","Meals are allowed.","Clean the area fully after eating.","Wipe the table before leaving.","Do not remain longer when another person is waiting."]'::jsonb,
  15, 30, 45, array[30,45], 'Up to 3 people', 4
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  location = excluded.location,
  purpose = excluded.purpose,
  compact_description = excluded.compact_description,
  recommended_uses = excluded.recommended_uses,
  guidelines = excluded.guidelines,
  booking_increment_minutes = excluded.booking_increment_minutes,
  minimum_duration_minutes = excluded.minimum_duration_minutes,
  maximum_duration_minutes = excluded.maximum_duration_minutes,
  allowed_durations_minutes = excluded.allowed_durations_minutes,
  capacity_label = excluded.capacity_label,
  display_order = excluded.display_order;

alter table public.rooms enable row level security;
alter table public.bookings enable row level security;
alter table public.room_blocks enable row level security;

revoke all on public.rooms, public.bookings, public.room_blocks
  from anon, authenticated;
revoke execute on function public.playbook_lock_key(text, date)
  from public, anon, authenticated;
revoke execute on function public.create_booking(
  text, text, text, date, integer, integer, text, text, text, text, timestamptz
) from public, anon, authenticated;
revoke execute on function public.update_booking(
  bigint, text, date, integer, integer, text, text, text, text, timestamptz
) from public, anon, authenticated;
revoke execute on function public.cancel_booking(bigint, timestamptz)
  from public, anon, authenticated;

grant select, insert, update, delete
  on public.rooms, public.bookings, public.room_blocks to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.playbook_lock_key(text, date)
  to service_role;
grant execute on function public.create_booking(
  text, text, text, date, integer, integer, text, text, text, text, timestamptz
) to service_role;
grant execute on function public.update_booking(
  bigint, text, date, integer, integer, text, text, text, text, timestamptz
) to service_role;
grant execute on function public.cancel_booking(bigint, timestamptz)
  to service_role;
